#!/usr/bin/python

#magric from http://stackoverflow.com/questions/221455/ghostscript-pdf-tiff-conversion-is-awful-for-me-people-rave-about-it-i-alon
#
#gm convert -define quantum:polarity=min-is-white \
#        -endian MSB \
#        -units PixelsPerInch \
#        -density 204x196 \
#        -monochrome \
#        -compress Fax \
#        -sample 1728 \
#        "changes_la.pdf" "output.tif"

import subprocess

subprocess.call(['gm', 'convert', '-define', 'quantum:polarity=min-is-white',
                '-endian','MSB', '-units','PixelsPerInch', '-density','204x196',
                '-compress', 'Fax', '-sample','1728',
                'changes_la.pdf', 'changes_la.tif'])
